CREATE TABLE "sessions" ("id" uuid PRIMARY KEY, "candidate_token_hash" text NOT NULL UNIQUE, "report_token_hash" text NOT NULL, "report_token_ciphertext" text NOT NULL, "challenge_id" text NOT NULL, "challenge_version" integer NOT NULL, "language" text NOT NULL, "candidate_name" text NOT NULL, "status" text NOT NULL, "revision" integer NOT NULL DEFAULT 0, "snapshot" jsonb NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now());
CREATE INDEX "sessions_created_at_idx" ON "sessions" ("created_at");
CREATE TABLE "session_files" ("id" uuid PRIMARY KEY, "session_id" uuid NOT NULL REFERENCES "sessions"("id") ON DELETE CASCADE, "path" text NOT NULL, "status" text NOT NULL, "base_content" text NOT NULL, "head_content" text NOT NULL, "saved_content" text);
CREATE INDEX "session_files_session_idx" ON "session_files" ("session_id");
CREATE TABLE "review_comments" ("id" uuid PRIMARY KEY, "session_id" uuid NOT NULL REFERENCES "sessions"("id") ON DELETE CASCADE, "file" text NOT NULL, "line" integer NOT NULL, "end_line" integer, "body" text NOT NULL, "state" text NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL);
CREATE INDEX "review_comments_session_idx" ON "review_comments" ("session_id");
CREATE TABLE "file_revisions" ("id" uuid PRIMARY KEY, "session_id" uuid NOT NULL REFERENCES "sessions"("id") ON DELETE CASCADE, "revision" integer NOT NULL, "files" jsonb NOT NULL, "created_at" timestamptz NOT NULL);
CREATE INDEX "file_revisions_session_revision_idx" ON "file_revisions" ("session_id", "revision");
CREATE TABLE "check_runs" ("id" uuid PRIMARY KEY, "session_id" uuid NOT NULL REFERENCES "sessions"("id") ON DELETE CASCADE, "revision" integer NOT NULL, "status" text NOT NULL, "results" jsonb NOT NULL, "created_at" timestamptz NOT NULL, "completed_at" timestamptz);
CREATE INDEX "check_runs_session_idx" ON "check_runs" ("session_id");
CREATE TABLE "ai_assessments" ("id" uuid PRIMARY KEY, "session_id" uuid NOT NULL REFERENCES "sessions"("id") ON DELETE CASCADE, "based_on_event_id" bigint NOT NULL, "revision" integer NOT NULL, "assessment" jsonb NOT NULL, "created_at" timestamptz NOT NULL);
CREATE INDEX "ai_assessments_session_revision_idx" ON "ai_assessments" ("session_id", "revision");
CREATE TABLE "interviewer_notes" ("session_id" uuid PRIMARY KEY REFERENCES "sessions"("id") ON DELETE CASCADE, "body" text NOT NULL, "updated_at" timestamptz NOT NULL);
CREATE TABLE "session_events" ("id" bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, "session_id" uuid NOT NULL REFERENCES "sessions"("id") ON DELETE CASCADE, "type" text NOT NULL, "actor" text NOT NULL, "payload" jsonb NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now());
CREATE INDEX "session_events_cursor_idx" ON "session_events" ("session_id", "id");
