"use client";

import { useMemo, useState } from "react";
import { CheckCircle2, ChevronRight, CircleDot, Code2, FileCode2, GitCommitHorizontal, MessageSquare, PanelLeft } from "lucide-react";
import type { CandidateSession } from "@/lib/candidate";
import type { ReviewComment } from "@/lib/types";
import { PrDiff } from "./PrDiff";

export function ReviewWorkspace({ session, token, onPhaseChange }: { session: CandidateSession; token: string; onPhaseChange: () => void }) {
  const [tab, setTab] = useState("files"); const [comments, setComments] = useState(session.comments); const [activeFile, setActiveFile] = useState(session.files[0]?.path ?? "");
  const [composer, setComposer] = useState<{ line: number; endLine: number } | null>(null); const [draft, setDraft] = useState(""); const [overallNote, setOverallNote] = useState(""); const [busy, setBusy] = useState(false); const [treeOpen, setTreeOpen] = useState(false);
  const file = session.files.find((item) => item.path === activeFile) ?? session.files[0];
  const stats = useMemo(() => session.files.reduce((acc, item) => ({ add: acc.add + item.headContent.split("\n").length, del: acc.del + item.baseContent.split("\n").length }), { add: 0, del: 0 }), [session.files]);
  async function add() { if (!composer || !draft.trim()) return; setBusy(true); const res = await fetch(`/api/candidate/${token}/comments`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ file: file.path, line: composer.line, endLine: composer.endLine === composer.line ? undefined : composer.endLine, body: draft }) }); const data = await res.json(); if (res.ok) { setComments((items) => [...items, data.comment]); setComposer(null); setDraft(""); } setBusy(false); }
  async function remove(id: string) { const previous = comments; setComments((items) => items.filter((item) => item.id !== id)); const res = await fetch(`/api/candidate/${token}/comments?id=${id}`, { method: "DELETE" }); if (!res.ok) setComments(previous); }
  async function submit() { setBusy(true); const res = await fetch(`/api/candidate/${token}/submit`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ overallNote }) }); if (res.ok) onPhaseChange(); else setBusy(false); }
  return <main className="pr-app">
    <PrTop session={session} phase="Review" />
    <div className="pr-summary"><div><span className="open-pill"><CircleDot size={14}/> Open</span><h1>{session.challenge.prTitle} <span>#{session.challenge.metadata.prNumber}</span></h1><p><strong>{session.challenge.metadata.author}</strong> wants to merge into <code>{session.challenge.metadata.baseBranch}</code> from <code>{session.challenge.metadata.headBranch}</code></p></div><button className="icon-button mobile-only" onClick={() => setTreeOpen(!treeOpen)}><PanelLeft size={18}/></button></div>
    <nav className="pr-tabs">
      <Tab id="conversation" tab={tab} setTab={setTab} icon={<MessageSquare/>} label="Conversation" count={comments.length}/><Tab id="commits" tab={tab} setTab={setTab} icon={<GitCommitHorizontal/>} label="Commits" count={1}/><Tab id="checks" tab={tab} setTab={setTab} icon={<CheckCircle2/>} label="Checks"/><Tab id="files" tab={tab} setTab={setTab} icon={<Code2/>} label="Files changed" count={session.files.length}/><span className="tab-stats"><b>+{stats.add}</b> <i>−{stats.del}</i></span>
    </nav>
    {tab === "files" ? <div className="candidate-layout">
      <aside className={`file-rail ${treeOpen ? "drawer-open" : ""}`}><h3>Files changed <span>{session.files.length}</span></h3>{session.files.map((item) => <button className={item.path === file.path ? "active" : ""} key={item.path} onClick={() => {setActiveFile(item.path); setTreeOpen(false)}}><FileCode2 size={15}/><span>{item.path}</span><b>{comments.filter((c) => c.file === item.path).length || ""}</b></button>)}</aside>
      <section className="review-canvas"><div className="review-instruction"><strong>Review the proposed changes</strong><span>Click any new line number to start a comment. Markdown is supported.</span></div><PrDiff file={file} comments={comments} onLine={(line) => setComposer({ line, endLine: line })}/>
        {composer ? <div className="review-composer"><div className="composer-anchor">Comment on {file.path}:{composer.line}{composer.endLine !== composer.line ? `–${composer.endLine}` : ""}</div><textarea autoFocus value={draft} onChange={(e) => setDraft(e.target.value)} placeholder="Leave feedback like you would on a pull request…"/><div className="composer-actions"><label>End line <input type="number" min={composer.line} value={composer.endLine} onChange={(e) => setComposer({ ...composer, endLine: Math.max(composer.line, Number(e.target.value)) })}/></label><button onClick={() => setComposer(null)}>Cancel</button><button className="primary" disabled={busy || !draft.trim()} onClick={add}>Start a review</button></div></div> : null}
      </section>
      <aside className="review-rail"><h3>Review summary</h3><p>{comments.length} draft comment{comments.length === 1 ? "" : "s"}</p>{comments.map((comment) => <div className="draft-card" key={comment.id}><code>{comment.file}:{comment.line}</code><p>{comment.body}</p><button onClick={() => remove(comment.id)}>Delete draft</button></div>)}<textarea value={overallNote} onChange={(e) => setOverallNote(e.target.value)} placeholder="Overall review summary (optional)"/><button className="primary full" disabled={busy} onClick={submit}>Submit review</button><small>Submitting moves you to the implementation phase.</small></aside>
    </div> : <CandidateTab tab={tab} session={session} comments={comments}/>}
  </main>;
}

export function PrTop({ session, phase }: { session: CandidateSession; phase: string }) { return <><header className="app-top"><a className="brand" href="#"><span>IV</span>Inter-View</a><div className="repo-crumb"><strong>{session.challenge.metadata.owner}</strong><ChevronRight/><span>{session.challenge.metadata.repository}</span><em>Private</em></div><div className="session-meta"><span className="live-dot"/>Live session <strong>{phase}</strong></div></header></>; }
function Tab({ id, tab, setTab, icon, label, count }: { id: string; tab: string; setTab: (id: string) => void; icon: React.ReactNode; label: string; count?: number }) { return <button className={tab === id ? "active" : ""} onClick={() => setTab(id)}>{icon}{label}{count !== undefined ? <b>{count}</b> : null}</button>; }
function CandidateTab({ tab, session, comments }: { tab: string; session: CandidateSession; comments: ReviewComment[] }) { return <section className="empty-tab">{tab === "conversation" ? <><MessageSquare size={28}/><h2>Pull request conversation</h2><p>{session.challenge.prDescription}</p>{comments.map((c) => <div className="conversation-comment" key={c.id}><code>{c.file}:{c.line}</code><p>{c.body}</p></div>)}</> : tab === "commits" ? <><GitCommitHorizontal size={28}/><h2>1 virtual commit</h2><div className="commit-row"><span>{session.challenge.metadata.author}</span><strong>{session.challenge.prTitle}</strong><code>seeded-pr</code></div></> : <><CheckCircle2 size={28}/><h2>Checks run after you edit</h2><p>Visible tests and category-level hidden results will appear here during the implementation phase.</p></>}</section>; }
